mod 'qtechnologies-nginx', '1.3.2'
mod 'puppetlabs-stdlib', '8.1.0'
mod 'qtechnologies-phpfpm', '1.1.2'
mod 'qtechnologies-psgi', '1.1.1'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '4.2.1'
